baseurl = "https://sunset1024star.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Wish me to be your Excalibur"
theme = "dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "#fff"
  # backgroundImage = "/me/6._clear.jpg"
  linkColor = "seagreen"

  # dark mode
  # defaultDark = true
  # backgroundDark = "#333"
  # backgroundImageDark = "/me/6._clear.jpg"
  # darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  images = ["me/background.jpg"]

  author = "LiLisaber"
  # description = "LiLisaber的学习记录～"
  avatar = "/me/8.jpg"
  headerTitle = "LiLisaber的博客"
  motto = "曾经沧海难为水，除却巫山不是云"
  # maxTags = 5
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  # rss = true

  # utterancesRepo = "sunset1024star/sunset1024star.github.io"

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  # VALINE_LANGUAGE = ""

  email = "514563580@qq.com"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  # linkedin = ""
  # github = "https://github.com/sunset1024star/"
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2022

  # favicon = "/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["clojure", "ocaml"]
  # highlightjsTheme = "tomorrow"
  # highlightjsThemeDark = "tomorrow-night"

  # search
  # enableSearch = true

  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # reversePostAndAside = true
  # shareInAside = true
  # fixedNav = true
  # collapsibleTags = true
  # collapseBySummary = true

  # [params.advanced]
  #   customCSS = ["css/custom.css"]
  #   customJSBefore = []
  #   customJS = []

  # [params.experimental]
  #   jsDate = true
  #   jsDateFormat = "yyyy年MM月dd日"
